import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { env } from "../env.ts";

// The appliance agent serves a self-signed cert generated by the bootstrap
// script. The UI has no other way to learn that cert's identity, so we report
// its SHA-256 fingerprint on /v1/info and the UI pins it in
// `user.k8s.api-config` (see docs/k8s/management-appliance.md §6). Format is
// "sha256:<hex>", matching the digest Incus itself prints for certificates.

let cached: string | null | undefined;

/** Fingerprint of the served TLS cert, or null when running plain HTTP (dev). */
export function serverCertFingerprint(): string | null {
  if (cached !== undefined) return cached;
  cached = computeFingerprint();
  return cached;
}

function computeFingerprint(): string | null {
  const path = env.TLS_CERT_FILE;
  if (!path) return null;
  try {
    const der = pemToDer(readFileSync(path, "utf8"));
    if (!der) return null;
    return `sha256:${createHash("sha256").update(der).digest("hex")}`;
  } catch {
    return null;
  }
}

function pemToDer(pem: string): Buffer | null {
  const match = pem.match(
    /-----BEGIN CERTIFICATE-----([\s\S]*?)-----END CERTIFICATE-----/,
  );
  const body = match?.[1]?.replace(/\s+/g, "");
  if (!body) return null;
  return Buffer.from(body, "base64");
}
