// Cluster specs → CAPN template variables. A port of the UI generator
// (packages/ui/src/util/k8s/capn.ts `buildTemplateVariables`) behind a
// friendlier option shape; the defaults match the UI's create form.

import type { CreateClusterRequest } from "./types";

/**
 * Prebuilt kubeadm images on the default CAPN simplestreams remote
 * (images.linuxcontainers.org/capn), newest first. Mirrors the UI list.
 */
export const KUBEADM_VERSIONS = [
  "v1.37.0",
  "v1.36.4",
  "v1.36.1",
  "v1.35.5",
  "v1.35.0",
  "v1.34.0",
  "v1.33.5",
  "v1.33.0",
] as const;

export const DEFAULT_KUBERNETES_VERSION = KUBEADM_VERSIONS[0];

/** kubeadm's preflight minimums for a control-plane node. */
export const CONTROL_PLANE_MIN_CPU = 2;
export const CONTROL_PLANE_MIN_MEMORY_MIB = 1700;

/** CAPN `c<cores>-m<GiB>` flavor, or a cloud instance type (`t3.medium`). */
export type Flavor = string | { cpu: number; memoryGiB: number };

export interface MachinePoolOptions {
  /** Default: 1 control-plane node, 1 worker. */
  count?: number;
  /** Default `container`. */
  type?: "container" | "virtual-machine" | "vm";
  /** Default `c2-m4` (2 CPUs, 4 GiB). */
  flavor?: Flavor;
  /** Incus profiles applied to the nodes. Default `["default"]`. */
  profiles?: string[];
  /** Incus cluster member or group (`@group`) to place the nodes on. */
  target?: string;
}

/** How the control-plane endpoint is exposed. */
export type LoadBalancerOptions =
  | { type: "lxc" | "oci"; profiles?: string[]; flavor?: Flavor }
  | { type: "kube-vip"; host: string }
  | { type: "ovn"; host: string; network: string };

export interface ClusterSpec {
  /** Cluster name (also the CAPI Cluster name), max 63 chars. */
  name: string;
  /** `vX.Y.Z`; default the newest prebuilt kubeadm image. */
  kubernetesVersion?: string;
  controlPlane?: MachinePoolOptions;
  workers?: MachinePoolOptions;
  /** Default: an LXC haproxy container (`c1-m1`). */
  loadBalancer?: LoadBalancerOptions;
  /** Incus project for the cluster (default: generated by the agent). */
  project?: string;
  /** Privileged node containers (default `true`, required by kubeadm in containers). */
  privileged?: boolean;
  /** Deploy flannel as the CNI (default `true`; nodes never get Ready without a CNI). */
  flannel?: boolean;
  /** Install kubeadm on boot — for custom images without it. */
  installKubeadm?: boolean;
  /** Custom node image (`LXC_IMAGE_NAME`) instead of the prebuilt kubeadm image. */
  image?: string;
  /** Default `10.244.0.0/16`. */
  podCidr?: string;
  /** Default `10.96.0.0/12`. */
  serviceCidr?: string;
  /** Raw CAPN template variables, applied last. */
  variables?: Record<string, string>;
  /**
   * Install MetalLB with these addresses once the cluster is first ready
   * (see `K8sClient.metallbHint` for a free range). Agent 0.3.0+.
   */
  metallb?: string[];
}

/** `{cpu: 2, memoryGiB: 4}` → `c2-m4`; strings pass through. */
export const flavorString = (flavor: Flavor): string => {
  if (typeof flavor === "string") return flavor.trim();
  const gib = Number.isInteger(flavor.memoryGiB)
    ? flavor.memoryGiB
    : Number(flavor.memoryGiB.toFixed(2));
  return `c${flavor.cpu}-m${gib}`;
};

/** CPU + memory of a `c<cores>-m<GiB>` flavor, or null for other names. */
export const parseFlavor = (
  flavor: string,
): { cpu: number; memoryMiB: number } | null => {
  const match = /^c(\d+)-m(\d+(?:\.\d+)?)$/.exec(flavor.trim());
  if (!match) return null;
  return {
    cpu: Number(match[1]),
    memoryMiB: Math.round(Number(match[2]) * 1024),
  };
};

/** Why a control-plane flavor cannot bootstrap kubeadm, or null. */
export const controlPlaneSizeError = (flavor: string): string | null => {
  const size = parseFlavor(flavor);
  if (!size) return null;
  if (size.cpu < CONTROL_PLANE_MIN_CPU) {
    return `control plane needs at least ${CONTROL_PLANE_MIN_CPU} CPUs (kubeadm refuses to initialize with fewer); got '${flavor}'`;
  }
  if (size.memoryMiB < CONTROL_PLANE_MIN_MEMORY_MIB) {
    return `control plane needs at least ${CONTROL_PLANE_MIN_MEMORY_MIB} MiB of memory (kubeadm refuses to initialize with less); got '${flavor}'`;
  }
  return null;
};

const machineType = (type: MachinePoolOptions["type"]): string =>
  type === "vm" ? "virtual-machine" : (type ?? "container");

const yamlList = (items: string[]): string => `[${items.join(", ")}]`;

const loadBalancerValue = (lb: LoadBalancerOptions): string => {
  switch (lb.type) {
    case "kube-vip":
      return `kube-vip: {host: ${lb.host}}`;
    case "ovn":
      return `ovn: {host: ${lb.host}, networkName: ${lb.network}}`;
    default:
      return `${lb.type}: {profiles: ${yamlList(lb.profiles ?? ["default"])}, flavor: ${flavorString(lb.flavor ?? "c1-m1")}}`;
  }
};

/**
 * CAPN template variables for a spec — the same map the UI's create form
 * sends (and previews). Throws if the control plane is too small for kubeadm.
 */
export const buildTemplateVariables = (
  spec: ClusterSpec,
): Record<string, string> => {
  const cp = spec.controlPlane ?? {};
  const workers = spec.workers ?? {};
  const cpFlavor = flavorString(cp.flavor ?? "c2-m4");
  const sizeError = controlPlaneSizeError(cpFlavor);
  if (sizeError) throw new Error(sizeError);

  const vars: Record<string, string> = {
    CLUSTER_NAME: spec.name,
    KUBERNETES_VERSION: spec.kubernetesVersion ?? DEFAULT_KUBERNETES_VERSION,
    LOAD_BALANCER: loadBalancerValue(spec.loadBalancer ?? { type: "lxc" }),
    CONTROL_PLANE_MACHINE_COUNT: String(cp.count ?? 1),
    WORKER_MACHINE_COUNT: String(workers.count ?? 1),
    CONTROL_PLANE_MACHINE_TYPE: machineType(cp.type),
    WORKER_MACHINE_TYPE: machineType(workers.type),
    CONTROL_PLANE_MACHINE_FLAVOR: cpFlavor,
    WORKER_MACHINE_FLAVOR: flavorString(workers.flavor ?? "c2-m4"),
  };
  // `default` is CAPN's own default; only set non-default profile lists.
  if (cp.profiles?.length && cp.profiles.join(",") !== "default") {
    vars.CONTROL_PLANE_MACHINE_PROFILES = yamlList(cp.profiles);
  }
  if (workers.profiles?.length && workers.profiles.join(",") !== "default") {
    vars.WORKER_MACHINE_PROFILES = yamlList(workers.profiles);
  }
  if (cp.target?.trim()) vars.CONTROL_PLANE_MACHINE_TARGET = cp.target.trim();
  if (workers.target?.trim())
    vars.WORKER_MACHINE_TARGET = workers.target.trim();

  vars.PRIVILEGED = String(spec.privileged ?? true);
  vars.DEPLOY_KUBE_FLANNEL = String(spec.flannel ?? true);
  if (spec.installKubeadm) vars.INSTALL_KUBEADM = "true";
  if (spec.image?.trim()) vars.LXC_IMAGE_NAME = spec.image.trim();
  vars.POD_CIDR = `[${spec.podCidr ?? "10.244.0.0/16"}]`;
  vars.SERVICE_CIDR = `[${spec.serviceCidr ?? "10.96.0.0/12"}]`;
  return { ...vars, ...spec.variables };
};

/** The agent's `POST /v1/clusters` body for a spec. */
export const createClusterRequest = (
  spec: ClusterSpec,
): CreateClusterRequest => {
  const variables = buildTemplateVariables(spec);
  return {
    name: spec.name,
    kubernetesVersion: variables.KUBERNETES_VERSION,
    controlPlaneCount: Number(variables.CONTROL_PLANE_MACHINE_COUNT),
    workerCount: Number(variables.WORKER_MACHINE_COUNT),
    project: spec.project,
    variables,
    ...(spec.metallb?.length ? { metallb: { addresses: spec.metallb } } : {}),
  };
};

const parseVersion = (version: string) => {
  const match = /^v(\d+)\.(\d+)\.(\d+)$/.exec(version.trim());
  return match
    ? {
        major: Number(match[1]),
        minor: Number(match[2]),
        patch: Number(match[3]),
      }
    : null;
};

/**
 * Versions a cluster on `current` can upgrade to, newest first: same major,
 * newer, at most one minor ahead (kubeadm's rule, enforced by the agent too).
 */
export const upgradeTargets = (
  current: string,
  available: readonly string[] = KUBEADM_VERSIONS,
): string[] => {
  const from = parseVersion(current);
  if (!from) return [];
  return available.filter((candidate) => {
    const to = parseVersion(candidate);
    if (!to || to.major !== from.major) return false;
    const newer =
      to.minor > from.minor ||
      (to.minor === from.minor && to.patch > from.patch);
    return newer && to.minor - from.minor <= 1;
  });
};
