import { IncusAPIClient } from "../api/client";
import type { EventOf, EventsOptions, EventSubscription } from "../api/events";
import type { InstanceListOptions } from "../api/instances";
import type { ListOptions } from "../api/base/types";
import type {
  CertificatesPost,
  DevicesMap,
  InstanceSource,
  NetworksPost,
  Operation,
  ProfilesPost,
  ProjectsPost,
  Server,
  StoragePoolsPost,
  EventType,
} from "../api/types/generated";
import { tokenFromOperation } from "../api/certificates";
import {
  DEFAULT_REMOTES,
  imageSource,
  type ImageRemote,
} from "../utils/helpers";
import type { DeepPartial, Input } from "../utils/types";
import { Certificate } from "./Certificate";
import { ClusterMember } from "./ClusterMember";
import { Image } from "./Image";
import { Instance } from "./Instance";
import { Network } from "./Network";
import { IncusOperation, type OperationWaitOptions } from "./Operation";
import { Profile } from "./Profile";
import { Project } from "./Project";
import { StoragePool } from "./StoragePool";

export interface CreateInstanceOptions extends OperationWaitOptions {
  /** Instance name (generated by the daemon when omitted). */
  name?: string;
  /**
   * Image reference: `"images:debian/12"`, `"docker:nginx"`, a local alias
   * or fingerprint. `null`/omitted creates an empty instance.
   */
  image?: string | null;
  /** Default `container`. */
  type?: "container" | "virtual-machine" | "vm";
  profiles?: string[];
  config?: Record<string, string>;
  devices?: DevicesMap;
  description?: string;
  ephemeral?: boolean;
  /** Cloud-style size, e.g. `c2-m4` (2 CPUs, 4GiB) or an AWS/GCP/Azure type. */
  instanceType?: string;
  /** Start once created. */
  start?: boolean;
  /** Cluster member to create it on. */
  target?: string;
  /** Raw `source` override (takes precedence over `image`). */
  source?: DeepPartial<InstanceSource>;
}

/**
 * Humane Incus client: object-oriented access where actions wait for their
 * background operations and return rich objects.
 *
 * @example
 * const client = createIncusClient({ url: "https://incus:8443" });
 * const web = await client.launchInstance({ name: "web", image: "images:debian/12" });
 * console.log(web.addresses);
 */
export class IncusClient {
  /** The stateless API client, for anything not wrapped here. */
  readonly $api: IncusAPIClient;
  /** Remotes resolvable in image references (`"remote:alias"`). */
  readonly remotes: Record<string, ImageRemote>;
  private extensions?: Promise<Set<string>>;

  constructor(
    api: IncusAPIClient,
    remotes: Record<string, ImageRemote> = DEFAULT_REMOTES,
  ) {
    this.$api = api;
    this.remotes = remotes;
  }

  /** Default project of this client. */
  get project(): string | undefined {
    return this.$api.project;
  }

  /** A client for another project (sharing the connection). */
  useProject(project: string): IncusClient {
    return new IncusClient(this.$api.withProject(project), this.remotes);
  }

  /** A client that targets a cluster member. */
  useTarget(target: string | undefined): IncusClient {
    return new IncusClient(this.$api.withTarget(target), this.remotes);
  }

  /** Wraps an operation from the raw API. */
  operation(op: Operation): IncusOperation {
    return new IncusOperation(this.$api, op);
  }

  // ─── Server ──────────────────────────────────────────────────────────────

  info(): Promise<Server> {
    return this.$api.server.info();
  }

  /** Whether the server supports an API extension (cached per client). */
  async hasExtension(name: string): Promise<boolean> {
    this.extensions ??= this.info().then(
      (s) => new Set(s.api_extensions ?? []),
    );
    return (await this.extensions).has(name);
  }

  /** Subscribes to daemon events. */
  on<K extends EventType>(
    types: K | K[],
    handler: (event: EventOf<K>) => void,
    opts: Omit<EventsOptions<K>, "types"> = {},
  ): Promise<EventSubscription> {
    return this.$api.events.subscribe(
      { ...opts, types: Array.isArray(types) ? types : [types] },
      handler,
    );
  }

  // ─── Instances ───────────────────────────────────────────────────────────

  /** Lists instances; `full` also loads state, snapshots and backups. */
  async listInstances(
    opts: InstanceListOptions & { full?: boolean } = {},
  ): Promise<Instance[]> {
    const list = opts.full
      ? await this.$api.instances.listFull(opts)
      : await this.$api.instances.list(opts);
    return list.map((i) => new Instance(this, i));
  }

  /** Gets an instance with its state, snapshots and backups. */
  async getInstance(name: string): Promise<Instance> {
    return new Instance(this, await this.$api.instance(name).getFull());
  }

  /** Creates an instance and waits until it exists (and runs, with `start`). */
  async createInstance(opts: CreateInstanceOptions): Promise<Instance> {
    const op = await this.$api.instances.create(
      {
        name: opts.name,
        type:
          opts.type === "vm" ? "virtual-machine" : (opts.type ?? "container"),
        source: opts.source ?? imageSource(opts.image, this.remotes),
        profiles: opts.profiles,
        config: opts.config,
        devices: opts.devices,
        description: opts.description,
        ephemeral: opts.ephemeral,
        instance_type: opts.instanceType,
        start: opts.start ?? false,
      },
      { target: opts.target },
    );
    const done = await this.operation(op).wait(opts);
    const url = done.resources?.instances?.[0];
    const name = opts.name ?? (url ? url.split("?")[0]!.split("/").pop()! : "");
    return this.getInstance(decodeURIComponent(name));
  }

  /** `createInstance` + start. */
  launchInstance(
    opts: Omit<CreateInstanceOptions, "start">,
  ): Promise<Instance> {
    return this.createInstance({ ...opts, start: true });
  }

  // ─── Images ──────────────────────────────────────────────────────────────

  async listImages(opts?: ListOptions): Promise<Image[]> {
    return (await this.$api.images.list(opts)).map((i) => new Image(this, i));
  }

  async getImage(fingerprint: string): Promise<Image> {
    return new Image(this, await this.$api.images.get(fingerprint));
  }

  async getImageByAlias(alias: string): Promise<Image> {
    return new Image(this, await this.$api.images.getByAlias(alias));
  }

  /**
   * Copies an image from a remote into the local store.
   *
   * @example
   * await client.copyImage("images:alpine/edge", { aliases: ["alpine"], autoUpdate: true });
   */
  async copyImage(
    ref: string,
    opts: OperationWaitOptions & {
      aliases?: string[];
      autoUpdate?: boolean;
      public?: boolean;
      type?: "container" | "virtual-machine";
    } = {},
  ): Promise<Image> {
    const source = imageSource(ref, this.remotes);
    const op = await this.$api.images.create({
      auto_update: opts.autoUpdate ?? false,
      public: opts.public ?? false,
      aliases: (opts.aliases ?? []).map((name) => ({ name })),
      source: {
        type: "image",
        mode: "pull",
        server: source.server,
        protocol: source.protocol,
        alias: source.alias,
        fingerprint: source.fingerprint,
        image_type: opts.type,
      },
    });
    const done = await this.operation(op).wait(opts);
    return this.getImage(String(done.metadata?.fingerprint ?? ""));
  }

  // ─── Profiles & projects ────────────────────────────────────────────────

  async listProfiles(opts?: ListOptions): Promise<Profile[]> {
    return (await this.$api.profiles.list(opts)).map(
      (p) => new Profile(this, p),
    );
  }

  async getProfile(name: string): Promise<Profile> {
    return new Profile(this, await this.$api.profiles.get(name));
  }

  async createProfile(body: Input<ProfilesPost, "name">): Promise<Profile> {
    await this.$api.profiles.create(body);
    return this.getProfile(body.name);
  }

  async listProjects(): Promise<Project[]> {
    return (await this.$api.projects.list()).map((p) => new Project(this, p));
  }

  async getProject(name: string): Promise<Project> {
    return new Project(this, await this.$api.projects.get(name));
  }

  async createProject(body: Input<ProjectsPost, "name">): Promise<Project> {
    await this.$api.projects.create(body);
    return this.getProject(body.name);
  }

  // ─── Networks ────────────────────────────────────────────────────────────

  async listNetworks(
    opts?: ListOptions & { managedOnly?: boolean },
  ): Promise<Network[]> {
    const networks = await this.$api.networks.list(opts);
    return networks
      .filter((n) => !opts?.managedOnly || n.managed)
      .map((n) => new Network(this, n));
  }

  async getNetwork(name: string): Promise<Network> {
    return new Network(this, await this.$api.networks.get(name));
  }

  async createNetwork(
    body: Input<NetworksPost, "name">,
    opts: { target?: string } = {},
  ): Promise<Network> {
    await this.$api.networks.create(body, opts);
    return this.getNetwork(body.name);
  }

  // ─── Storage ─────────────────────────────────────────────────────────────

  async listStoragePools(): Promise<StoragePool[]> {
    return (await this.$api.storagePools.list()).map(
      (p) => new StoragePool(this, p),
    );
  }

  async getStoragePool(name: string): Promise<StoragePool> {
    return new StoragePool(this, await this.$api.storagePools.get(name));
  }

  async createStoragePool(
    body: Input<StoragePoolsPost, "name" | "driver">,
    opts: { target?: string } = {},
  ): Promise<StoragePool> {
    await this.$api.storagePools.create(body, opts);
    return this.getStoragePool(body.name);
  }

  // ─── Trust ───────────────────────────────────────────────────────────────

  async listCertificates(): Promise<Certificate[]> {
    return (await this.$api.certificates.list()).map(
      (c) => new Certificate(this, c),
    );
  }

  async getCertificate(fingerprint: string): Promise<Certificate> {
    return new Certificate(this, await this.$api.certificates.get(fingerprint));
  }

  /** Trusts a client certificate (PEM, without the private key). */
  async addCertificate(
    body: Input<CertificatesPost, "certificate"> & { name: string },
  ): Promise<void> {
    await this.$api.certificates.create({ type: "client", ...body });
  }

  /**
   * Issues a trust token for a new client (`incus remote add <url> <token>`).
   * Returns the token string.
   */
  async createTrustToken(
    name: string,
    opts: { projects?: string[] } = {},
  ): Promise<string> {
    const op = await this.$api.certificates.createToken({
      name,
      projects: opts.projects,
      restricted: !!opts.projects?.length,
    });
    return tokenFromOperation(op);
  }

  // ─── Cluster ─────────────────────────────────────────────────────────────

  async listClusterMembers(): Promise<ClusterMember[]> {
    return (await this.$api.cluster.members.list()).map(
      (m) => new ClusterMember(this, m),
    );
  }

  async getClusterMember(name: string): Promise<ClusterMember> {
    return new ClusterMember(this, await this.$api.cluster.members.get(name));
  }
}
