package integration

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// writeFile writes content below dir, creating parent directories.
func writeFile(t *testing.T, dir string, name string, content string) {
	t.Helper()
	path := filepath.Join(dir, name)
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

func TestReadOVN(t *testing.T) {
	root := t.TempDir()
	// As MicroOVN 26.03 writes it.
	writeFile(t, root, "data/env/ovn.env", `# # Generated by MicroOVN, DO NOT EDIT.
OVN_INITIAL_NB="10.0.0.1"
OVN_NB_CONNECT="ssl:10.0.0.1:6641,ssl:10.0.0.2:6641"
OVN_SB_CONNECT="ssl:10.0.0.1:6642,ssl:10.0.0.2:6642"
`)
	writeFile(t, root, "data/pki/cacert.pem", "CA\n")
	writeFile(t, root, "data/pki/client-cert.pem", "CERT\n")
	writeFile(t, root, "data/pki/client-privkey.pem", "KEY\n")

	state, err := ReadOVN(root)
	require.NoError(t, err)
	require.Equal(t, map[string]string{
		KeyNorthbound: "ssl:10.0.0.1:6641,ssl:10.0.0.2:6641",
		KeyCACert:     "CA",
		KeyClientCert: "CERT",
		KeyClientKey:  "KEY",
	}, state.GlobalConfig())

	// Nothing to do when Incus has the same values, newline or not.
	current := map[string]string{
		KeyNorthbound: "ssl:10.0.0.1:6641,ssl:10.0.0.2:6641",
		KeyCACert:     "CA\n",
		KeyClientCert: "CERT",
		KeyClientKey:  "KEY",
	}

	require.Empty(t, Changes(current, state.GlobalConfig()))

	// A new central member only changes the connection string.
	current[KeyNorthbound] = "ssl:10.0.0.1:6641"
	require.Equal(t, map[string]string{KeyNorthbound: "ssl:10.0.0.1:6641,ssl:10.0.0.2:6641"}, Changes(current, state.GlobalConfig()))
}

func TestReadOVNIncomplete(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "data/env/ovn.env", "OVN_INITIAL_NB=\"10.0.0.1\"\n")
	_, err := ReadOVN(root)
	require.ErrorContains(t, err, "OVN_NB_CONNECT")

	_, err = ReadOVN(t.TempDir())
	require.Error(t, err)
}

func TestSyncCeph(t *testing.T) {
	src := t.TempDir()
	dst := filepath.Join(t.TempDir(), "ceph")
	writeFile(t, src, "ceph.conf", "[global]\nmon host = 10.0.0.1\n")
	writeFile(t, src, "ceph.keyring", "[client.admin]\nkey = secret\n")

	written, err := SyncCeph(src, dst)
	require.NoError(t, err)
	require.Len(t, written, 2)

	info, err := os.Stat(filepath.Join(dst, "ceph.client.admin.keyring"))
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o600), info.Mode().Perm())

	// Unchanged files are left alone.
	written, err = SyncCeph(src, dst)
	require.NoError(t, err)
	require.Empty(t, written)

	// A new monitor rewrites ceph.conf only.
	writeFile(t, src, "ceph.conf", "[global]\nmon host = 10.0.0.1,10.0.0.2\n")
	written, err = SyncCeph(src, dst)
	require.NoError(t, err)
	require.Equal(t, []string{filepath.Join(dst, "ceph.conf")}, written)

	content, err := os.ReadFile(filepath.Join(dst, "ceph.conf"))
	require.NoError(t, err)
	require.Contains(t, string(content), "10.0.0.2")
}

func TestHostIDs(t *testing.T) {
	ids, err := AssignHostIDs(nil, []string{"c", "a", "b"})
	require.NoError(t, err)
	require.Equal(t, map[string]int{"a": 1, "b": 2, "c": 3}, ids)
	require.Equal(t, "a=1,b=2,c=3", FormatHostIDs(ids))

	// b left the cluster but keeps its entry; d gets a fresh id.
	parsed, err := ParseHostIDs("a=1,b=2,c=3")
	require.NoError(t, err)
	ids, err = AssignHostIDs(parsed, []string{"a", "c", "d"})
	require.NoError(t, err)
	require.Equal(t, 4, ids["d"])
	require.Equal(t, 2, ids["b"])

	_, err = ParseHostIDs("a=0")
	require.Error(t, err)
	_, err = ParseHostIDs("a")
	require.Error(t, err)
}

func TestEnableLvmlockd(t *testing.T) {
	// Ubuntu's lvm.conf has the setting commented out in the global section.
	conf := "config {\n}\nglobal {\n\tumask = 077\n\t# use_lvmlockd = 0\n}\n"
	require.False(t, LockdEnabled(conf))

	out, err := EnableLvmlockd(conf)
	require.NoError(t, err)
	require.Equal(t, "config {\n}\nglobal {\n\tumask = 077\n\tuse_lvmlockd = 1\n}\n", out)
	require.True(t, LockdEnabled(out))

	// Idempotent.
	again, err := EnableLvmlockd(out)
	require.NoError(t, err)
	require.Equal(t, out, again)

	out, err = EnableLvmlockd("global {\n\tumask = 077\n}\n")
	require.NoError(t, err)
	require.Equal(t, "global {\n\tuse_lvmlockd = 1\n\tumask = 077\n}\n", out)

	_, err = EnableLvmlockd("devices {\n}\n")
	require.Error(t, err)

	require.Contains(t, LocalConf(3), "host_id = 3")
}
