import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

/**
 * Validated runtime configuration for the agent. Import-time validation means a
 * misconfigured agent fails fast on boot instead of at first request.
 */
export const env = createEnv({
  server: {
    HOST: z.string().default("0.0.0.0"),
    // Default 8843 to avoid colliding with the Incus HTTPS API (8443) when the
    // agent runs on the same host during dev.
    PORT: z.coerce.number().int().positive().max(65535).default(8843),
    // Bearer token the Incendio UI must present on every privileged request.
    AGENT_TOKEN: z.string().min(16, "AGENT_TOKEN must be at least 16 characters"),
    // Secret used to sign short-lived JWTs handed back to the UI.
    JWT_SECRET: z.string().min(16, "JWT_SECRET must be at least 16 characters"),
    // Comma-separated list of allowed browser origins, or "*" for any.
    CORS_ORIGIN: z.string().default("*"),
    // Incus HTTPS API endpoint the agent talks to on behalf of the UI.
    INCUS_API_URL: z.string().default("https://127.0.0.1:8443"),
    INCUS_CLIENT_CERT: z.string().optional(),
    INCUS_CLIENT_KEY: z.string().optional(),
    // Incus server certificate PEM path used to pin/verify TLS (the same
    // material as `server-crt` in the CAPN lxc-secret). Preferred over
    // INCUS_INSECURE_SKIP_VERIFY.
    INCUS_SERVER_CERT: z.string().optional(),
    INCUS_INSECURE_SKIP_VERIFY: z
      .enum(["true", "false"])
      .default("false")
      .transform((v) => v === "true"),
    LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
    // Kubeconfig for the local mgmt k3s cluster the agent brokers CAPI/CAPN
    // against. Matches the k3s default the bootstrap script installs.
    KUBECONFIG: z.string().default("/etc/rancher/k3s/k3s.yaml"),
    // clusterctl config carrying the `incus` InfrastructureProvider
    // registration (written by bootstrap.sh before `clusterctl init`).
    CLUSTERCTL_CONFIG: z.string().default("/etc/incendio/clusterctl.yaml"),
    // CAPN provider version, used for `--infrastructure incus:<version>`.
    CAPN_VERSION: z.string().default("v0.9.1"),
    // Control-plane endpoint load balancer type CAPN provisions for new
    // clusters. `lxc`/`oci` are zero-config haproxy instances.
    LOAD_BALANCER_TYPE: z.enum(["lxc", "oci"]).default("lxc"),
    // Storage pool / network for a workload project's `default` profile (CAPN
    // launches instances with `profiles: [default]`). Auto-detected from the
    // Incus API when unset.
    WORKLOAD_STORAGE_POOL: z.string().optional(),
    WORKLOAD_NETWORK: z.string().optional(),
    // MetalLB release installed into workload clusters on request (service
    // load balancer, L2 mode). The manifest URL overrides the GitHub one,
    // e.g. for a mirror.
    METALLB_VERSION: z.string().default("v0.16.0"),
    METALLB_MANIFEST_URL: z.string().optional(),
    // Path to the agent's sqlite cache/log DB. In the appliance the bootstrap
    // script points this at /opt/incendio; ":memory:" is handy for tests.
    DB_PATH: z.string().default("incendio-k8s.sqlite"),
    // Self-signed TLS material the agent serves with (see
    // docs/k8s/management-appliance.md §6). Generated by the bootstrap script;
    // when either is unset the agent falls back to plain HTTP (dev only).
    TLS_CERT_FILE: z.string().optional(),
    TLS_KEY_FILE: z.string().optional(),
  },
  runtimeEnv: process.env,
  emptyStringAsUndefined: true,
});
